spring:
  application.name: loco-back
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari.schema: ${DB_SCHEMA:loco}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate:
      format_sql: true
      default_schema: ${DB_SCHEMA:loco}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${YANDEX_ISSUER_URL:https://auth.yandex.cloud}

yandex:
  client-id: ${YANDEX_CLIENT_ID:yandex-client-id}
  client-secret: ${YANDEX_CLIENT_SECRET:yandex-client-secret}
  exchange-url: https://login.yandex.ru/info?format=jwt
